### ISSUE TITLE
Support for Apple Silicon devices

### ISSUE THREAD

**Issue by georgeogoodman** [hffqyd/tw5-server#6]
All my Mac devices are now based on Apple Silicon. Is there any way to get a build for that generation of platforms running macOS?

**Comment by hffqyd** [comment]
Since I'm using an Intel Mac, I cannot provide a release for Apple Silicon version currently. But you can compile one from the source code.

And I'm working on it to find a way to compile for Apple Silicon from my current version of macos. If it's done, I'll publish it in release.

Update: I've upload a new Apple Silicon version version to Relsease. Please download and have a try.

**Comment by georgeogoodman** [comment]
I've got the new release running on an Apple Macbook Pro with the M2 processor and all seems well. Thanks for this!
